/*
Even Fibonacci numbers

Each new term in the Fibonacci sequence is generated by adding the previous
two terms. By starting with 1 and 2, the first 10 terms will be:
  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.
*/

var countTo = 4000000;
var firstNumber = 1;
var secondNumber = 2;
var nextNumber = 0;
var sum = 2;  // This is kind of cheating? Find a better way.

while (nextNumber < countTo)
{
  nextNumber = firstNumber + secondNumber;
  firstNumber = secondNumber;
  secondNumber = nextNumber;

  if (nextNumber % 2 === 0)
  {
    sum += nextNumber;
  }
}

console.log("Considering the terms of the Fibonacci sequence whose values do "
  + "not exceed " + countTo + ", the sum of the even-valued terms is "
  + sum + ".");
